service: ecs-service

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  memorySize: 512
  timeout: 10
  variableSyntax: '\${{([\s\S]+?)}}'

functions:
  MyECS:
      handler: handler.lambda_handler
  IotDeviceConnection:
      handler: DeviceConnection.lambda_handler

resources:
  Resources:
    
    ApplicationLoadBalancerRecordSet:
      Type: "AWS::Route53::RecordSet"
      DependsOn: ["WebServerLoadBalancer"]
      Properties:
        AliasTarget:
          DNSName: !GetAtt WebServerLoadBalancer.Name
          EvaluateTargetHealth: "false"
          HostedZoneId: "ZV231HDRL6HIS"
        Name: 'webrpc.d2c-merapar.toon.eu.'
        Type: "A"

    #IoT RPC Device connection Rule
    IoTDeviceConnectionDymamoDBRule:
      Type: AWS::IoT::TopicRule
      Properties:
        RuleName: "DeviceConnectionRule"
        TopicRulePayload:
          RuleDisabled: "false"
          Sql: >-
            SELECT clientId, eventType,versionNumber FROM '$aws/events/presence/#'
          Actions:
            -
              Lambda:
                FunctionArn: { Fn::GetAtt: [IotDeviceConnectionLambdaFunction, Arn]}

    #IoT Rule
    LambdaIoTRule:
      Type: AWS::IoT::TopicRule
      Properties:
        RuleName: "ECSIOTRULE"
        TopicRulePayload:
          RuleDisabled: "false"
          Sql: >-  
            SELECT MessageInfo
          Actions:
            -
              Lambda:
                FunctionArn: { Fn::GetAtt: [MyECSLambdaFunction, Arn] }
    
    #IAM IoT Role
    TaskDefinitionRole:
      Type: AWS::IAM::Role
      Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - "ecs-tasks.amazonaws.com"
              Action:
                - "sts:AssumeRole"  
          Path: "/"
          Policies:
            -
              PolicyName: "TaskDefinitionPolicy"
              PolicyDocument:
                Version: "2012-10-17"
                Statement:
                  -
                    Effect: "Allow"
                    Action: ["iot:*", "ecs:*","ecr:*", "logs:*", "cloudwatch:*"]
                    Resource: "*"

    #ECS Cluster
    WebServerCluster:
      Type: AWS::ECS::Cluster
      Properties:
        ClusterName: "WebServerCluster"

    #ECR Repository
    WebInterfaceRepo:
      Type: AWS::ECR::Repository
      Properties:
        RepositoryName: "webapi"

    #TaskDefinition
    WebInterfaceTaskDefinition:
      Type: AWS::ECS::TaskDefinition
      DependsOn: [TaskDefinitionRole, WebInterfaceRepo]
      Properties:
          Cpu: 512
          Memory: 1024
          Family: "Web-Api"
          NetworkMode: "awsvpc"
          TaskRoleArn: 
            Ref: TaskDefinitionRole
          ExecutionRoleArn: !Ref TaskDefinitionRole
          RequiresCompatibilities: 
            - FARGATE
          ContainerDefinitions:
          - Name: "WebInterface"
            LogConfiguration:
              LogDriver: "awslogs"
              Options:
                awslogs-group: "/ecs/webapi"
                awslogs-region: "eu-west-1"
                awslogs-stream-prefix: "ecs"

            Image: !Sub '${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${WebInterfaceRepo}:latest'
            Cpu: 192
            MemoryReservation: 512
            PortMappings:
              - ContainerPort: 80
                Protocol: "tcp"
              - ContainerPort: 8080
                Protocol: "tcp"

    #TargetGroup
    WebServerTargetGroup:
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties:
        HealthCheckIntervalSeconds: 30
        HealthCheckPath: "/healthcheck"
        HealthCheckPort: "80"
        HealthCheckProtocol: "HTTP"
        HealthCheckTimeoutSeconds: 5
        HealthyThresholdCount: 5
        Name: "WebTargetGroup"
        Port: 80
        Protocol: "HTTP"
        UnhealthyThresholdCount: 2
        VpcId: "vpc-b25388d4"
        TargetType: "ip"
    
    #LoadBalancer
    WebServerLoadBalancer:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Properties:
        IpAddressType: "ipv4"
        Name: "ECS-Webserver-ALB"
        Scheme: "internet-facing"
        Subnets: ["subnet-c6211f9d", "subnet-33e21f55"]
        Type: "application"

    #LoadBalancer listener
    HTTPListener:
      Type: "AWS::ElasticLoadBalancingV2::Listener"
      DependsOn: ["WebServerLoadBalancer", "WebServerTargetGroup"]
      Properties:
        DefaultActions:
          - Type: "forward"
            TargetGroupArn: !Ref WebServerTargetGroup
        LoadBalancerArn: !Ref WebServerLoadBalancer
        Port: 80
        Protocol: "HTTP"
    
    #LoadBalancer HTTPS Listener
    HTTPSListener:
      Type: "AWS::ElasticLoadBalancingV2::Listener"
      DependsOn: ["WebServerLoadBalancer", "WebServerTargetGroup"]
      Properties:
        Certificates:
          CertificateArn: "arn:aws:acm:eu-west-1:740976047420:certificate/ae83eeab-0de3-45e7-aeca-cedcb1181d9b"
        DefaultActions:
          - Type: "forward"
            TargetGroupArn: !Ref WebServerTargetGroup
        LoadBalancerArn: !Ref WebServerLoadBalancer
        Port: 443
        Protocol: "HTTPS"
  
    #ECS Service
    WebServerService:
      Type: "AWS::ECS::Service"
      DependsOn: ["WebServerCluster","WebInterfaceTaskDefinition","ECSSecurityGroup", "HTTPListener", "HTTPSListener"]
      Properties:
        Cluster: !Ref WebServerCluster
        DesiredCount: 2
        LaunchType: "FARGATE"
        LoadBalancers:
          - 
            ContainerName: "WebInterface"
            ContainerPort: 80
            TargetGroupArn: !Ref WebServerTargetGroup
               
        NetworkConfiguration:
          AwsvpcConfiguration:
            AssignPublicIp: "ENABLED"
            SecurityGroups: [!Ref ECSSecurityGroup]
            Subnets: ["subnet-c6211f9d", "subnet-33e21f55"]
        ServiceName: "WebServerService"
        SchedulingStrategy: "REPLICA"
        TaskDefinition: !Ref WebInterfaceTaskDefinition
        
    #ECS Service SecurityGroup
    ECSSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
        GroupDescription: "Internetfacing group" #required
        GroupName: "SSH and HTTP"
        SecurityGroupEgress:
            - IpProtocol: -1
              CidrIp: "0.0.0.0/0"
          # - IpProtocol: "tcp"
          #   FromPort: '22'
          #   ToPort: '22'
          #   CidrIp: 0.0.0.0/0
          # - IpProtocol: "tcp"
          #   FromPort: '80'
          #   ToPort: '80'
          #   CidrIp: 0.0.0.0/0
          # - IpProtocol: "tcp"
          #   FromPort: '8080'
          #   ToPort: '8080'
          #   CidrIp: 0.0.0.0/0
        SecurityGroupIngress:
          - IpProtocol: -1
            CidrIp: 0.0.0.0/0
        VpcId: "vpc-b25388d4"
    

    #AutoScale Role
    WebServerAutoScalingRole:
      Type: "AWS::IAM::Role"
      Properties:
        AssumeRolePolicyDocument:
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service: ["application-autoscaling.amazonaws.com"]
              Action: ["sts:AssumeRole"]
        Path: "/"
        Policies:
          - 
            PolicyName: webserver-autoscaling-policy
            PolicyDocument:
              Statement:
              -
                Effect: "Allow"
                Action: ["application-autoscalling:*", "cloudwatch:*","ecs:*"]
                Resource: "*"

    #AutoScaleTarget
    WebServerAutoScalingTarget:
      Type: "AWS::ApplicationAutoScaling::ScalableTarget"
      DependsOn: ["WebServerAutoScalingRole", "WebServerService"]
      Properties:
        MaxCapacity: 8
        MinCapacity: 2
        ResourceId:
          Fn::Join:
            - "/"
            - - service
              - !Ref WebServerCluster
              - !GetAtt WebServerService.Name
        RoleARN: !GetAtt WebServerAutoScalingRole.Arn
        ScalableDimension: "ecs:service:DesiredCount"
        ServiceNamespace: "ecs"

    #Scaling Up Policy          
    ScaleUp:
      Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
      DependsOn: ["WebServerAutoScalingTarget"]
      Properties:
        PolicyName: webserver-scaling-up-policy #required
        PolicyType: "StepScaling" #required
        ScalingTargetId: !Ref "WebServerAutoScalingTarget"
        StepScalingPolicyConfiguration:
          Cooldown: 300
          AdjustmentType: "ChangeInCapacity"
          StepAdjustments:
            - MetricIntervalLowerBound: 0
              MetricIntervalUpperBound: 10
              ScalingAdjustment: 1
              
            - MetricIntervalLowerBound: 10
              MetricIntervalUpperBound: 20
              ScalingAdjustment: 2
            
            - MetricIntervalLowerBound: 20
              ScalingAdjustment: 3
    
    #Scaling Down Policy
    ScaleDown:
      Type: "AWS::ApplicationAutoScaling::ScalingPolicy"
      DependsOn: ["WebServerAutoScalingTarget"]
      Properties:
        PolicyName: "webserver-scaling-down-policy"
        PolicyType: "StepScaling"
        ScalingTargetId: !Ref WebServerAutoScalingTarget
        StepScalingPolicyConfiguration:
          Cooldown: 300
          AdjustmentType: "ChangeInCapacity"
          StepAdjustments:
            - MetricIntervalUpperBound: 0
              MetricIntervalLowerBound: -10
              ScalingAdjustment: -1

            - MetricIntervalUpperBound: -10
              ScalingAdjustment: -2

    #Cloudwatch Scaling Up Alarm
    CPUAlarmHigh:
      Type: "AWS::CloudWatch::Alarm"
      DependsOn: ["ScaleUp"]
      Properties:
        AlarmActions:
          - !Ref ScaleUp
        AlarmDescription: "scaling up alarm based on CPU metrics"
        AlarmName: "ecs-webserver->=30%-alarm"
        ComparisonOperator: "GreaterThanThreshold" #required
        Dimensions:
          - Name: !Ref WebServerCluster
            Value: !Ref WebServerService
        EvaluationPeriods: 2
        MetricName: CPUUtilization
        Namespace: "AWS/ECS"
        Period: 300
        Statistic: "Average"
        Threshold: 20

    #Cloudwatch Scaling Down Alarm
    CPUAlarmLow:
      Type: "AWS::CloudWatch::Alarm"
      DependsOn: ["ScaleDown"]
      Properties:
        AlarmActions:
          - !Ref "ScaleDown"
        AlarmDescription: "Scaling down alarm based on CPU metrics"
        AlarmName: "ecs-webserver-<=20%-alarm"
        ComparisonOperator: "LessThanThreshold" #required
        Dimensions:
          - Name: !Ref WebServerCluster
            Value: !Ref WebServerService
        EvaluationPeriods: 2
        MetricName: CPUUtilization
        Namespace: "AWS/ECS"
        Period: 300
        Statistic: "Average"
        Threshold: 20