service: ecs-service

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  memorySize: 512
  timeout: 10

functions:
  ECS:
      handler: handler.lambda_handler

resources:
  Resources:
    MyRule:
      Type: AWS::IoT::TopicRule
      Properties:
        RuleName: "ECSIOTRULE"
        TopicRulePayload:
          RuleDisabled: "false"
          Sql: >-
            SELECT MessageInfo FROM 'api/iot/lambda/pub/#'
          Actions:
            -
              Lambda: 
                FunctionArn: {Fn::GetAtt: [ ECSLambdaFunction, Arn ]}

    WebInterfaceTaskDefinition:
      Type: AWS::ECS::TaskDefinition
      Properties:
          Cpu: 256
          Memory: 1024
          Family: "Web-Api"
          NetworkMode: "awsvpc"
          TaskRoleArn: "arn:aws:iam::740976047420:role/ecsTaskExecutionRole"
          ExecutionRoleArn: "arn:aws:iam::740976047420:role/ecsTaskExecutionRole"
          RequiresCompatibilities: 
            - FARGATE
          ContainerDefinitions:
          - Name: "xray-daemon"
            Image: "740976047420.dkr.ecr.eu-west-1.amazonaws.com/xray-daemon:latest"
            Cpu: 32
            MemoryReservation: 256
            PortMappings:
              - ContainerPort: 2000
                Protocol: "udp"
          - Name: "Web-Interface"
            Image: "740976047420.dkr.ecr.eu-west-1.amazonaws.com/web-interface:latest"
            Cpu: 192
            MemoryReservation: 512