service: my-ecs-iot-service

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 10

functions:
  MyEcsLambdaFunction:
      handler: handler.lambda_handler.py

Resources:
  WebInterfaceTask:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Cpu: "256"
      Memory: "512"
      NetworkMode: "awsvpc"
      ExecutionRoleArn: "arn:aws:iam::740976047420:role/ecsTaskExecutionRole"
      TaskRoleArn: "arn:aws:iam::740976047420:role/ecsTaskExecutionRole"
      RequiresCompatibilities:
      - "FARGATE"
      ContainerDefinitions:
        - Name: "my-web-interface-task"
          Image: "740976047420.dkr.ecr.us-east-1.amazonaws.com/my-web-interface:latest"
          Memory: "500"
          
  LambdaRule:
    Type: AWS::IoT::TopicRule
    Properties:
      RuleName:
        Ref: "Lambda-IoT-Rule"
      TopicRulePayload:
        RuleDisabled: "false"
        Sql: >-
          SELECT * FROM 'api/iot/pub/#'
        Actions:
          -
            Republish:
              Topic: "api/iot/sub"
              RoleArn: "arn:aws:iam::740976047420:role/service-role/WebInterface-Subscribe"