service: my-ecs-iot-lambda-service

provider:
  name: aws
  runtime: python3.6
  memorySize: 512
  timeout: 10

functions:
  ECS:
      handler: handler.lambda_handler.py

resources:
  Resources:
    MyRule:
      Type: AWS::IoT::TopicRule
      Properties:
        RuleName: "MyRule"
        TopicRulePayload:
          RuleDisabled: "false"
          Sql: >-
            SELECT * FROM 'api/iot/lambda/pub/#'
          Actions:
            -
              Lambda:
                FunctionArn: {Fn::GetAtt: [ ECSLambdaFunction, Arn ]}